# Define the input text as a list of strings
input_text = '''
    "roma"
"its roma"
"its shridevi"
"my name is shridevi"
"i'm roma"
"my name is roma"
"I go by Sam"
"My full name is Emily Watson."
"Call me Lisa"
"I'm Alice"
"My full name is Emily Watson"
"Arbaaz Khan"
"My name is Marcus Jackson"
"Hey, it's John"
"Hey, I am Alex Parker"
"My name is Dhruv"
"Hello, I am Ananya Sharma."
"They call me Rajesh."
"My name's Christopher Green."
"It's Neha speaking."
"I'm known as Aman."
"You can call me Priya."
"My full name is Samantha Brown."
"Hey there, it's Arjun."
"The name is Monica."
"Hi, I'm Vikram Patel."
"My name is Sophia."
"Just call me Mike."
"Hello, this is Natasha."
"I'm Rahul."
"Hey, it's Emily Johnson."
"They know me as Ramesh."
"I'm Lisa Carter."
"My full name is Peter Parker."
"I go by Anjali."
"This is Zayn Malik."
"I’m Benjamin."
"My name is Isabella."
"People call me Nathan."
"You can refer to me as Akshay."
"It's Sarah Carter."
"Hi, I'm Rajesh Kumar."
"My name is Priya Singh."
"You can call me Ananya."
"I'm known as Rohan Malhotra."
"Hello, this is Meera Iyer."
"My full name is Akshay Verma."
"They call me Kavya."
"Hey, it's Arjun Nair."
"My name's Deepika Reddy."
"The name is Suresh."
"People call me Pooja."
"It's Ankit speaking."
"I go by Shreya."
"This is Aditya Sharma."
"I'm known as Sneha."
"My name is Abhishek."
"Call me Nisha."
"Hi, I'm Siddharth Rao."
"My full name is Arvind Joshi."
"Hey, I am Sunita."
"I'm Prakash."
"You can refer to me as Aditi."
"The name is Varun Kapoor."
"Hello, I’m Anita Pandey."
"Hi, this is Kartikeya."
'''

# Remove double quotes from the text
cleaned_text = input_text.replace('"', '')

# Write the cleaned text to a .txt file
output_file = "cleaned_output.txt"
with open(output_file, 'w') as file:
    file.write(cleaned_text)

print(f"Cleaned output saved to {output_file}")
